# Generated by Django 5.1.7 on 2025-08-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0006_tbl_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tutor_images/')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='adminapp.tbl_department')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hods', to='adminapp.tbl_hod')),
            ],
        ),
    ]
