# Generated by Django 5.1.7 on 2025-08-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_tutor',
            name='roles',
            field=models.CharField(default='tutor', max_length=100),
        ),
    ]
