# Generated by Django 5.1.7 on 2025-08-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0002_tbl_tutor_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_tutor',
            name='password',
        ),
        migrations.AddField(
            model_name='tbl_tutor',
            name='tutor_id',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
