# Generated by Django 5.1.7 on 2025-08-07 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_tbl_hod_password_tbl_hod_hod_id'),
        ('gatepassapp', '0003_remove_tbl_tutor_password_tbl_tutor_tutor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_tutor',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tutor_courses', to='adminapp.tbl_course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='Training_images/')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('supply', models.CharField(blank=True, max_length=100, null=True)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('register_number', models.CharField(max_length=50)),
                ('roll_number', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_department')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_hod')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatepassapp.tbl_tutor')),
            ],
        ),
    ]
