# Generated by Django 5.1.7 on 2025-08-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0004_tbl_tutor_course_tbl_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_student',
            name='role',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
