# Generated by Django 5.1.7 on 2025-08-08 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0005_tbl_student_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_student',
            name='image',
        ),
        migrations.CreateModel(
            name='StudentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='student_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gatepassapp.tbl_student')),
            ],
        ),
    ]
