# Generated by Django 5.1.7 on 2025-08-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0006_remove_tbl_student_image_studentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_tutor',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
