# Generated by Django 5.1.7 on 2025-08-23 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_tbl_tutor'),
        ('gatepassapp', '0007_tbl_tutor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_student',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_tutor'),
        ),
        migrations.DeleteModel(
            name='tbl_tutor',
        ),
    ]
