# Generated by Django 5.1.7 on 2025-08-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0008_alter_tbl_student_tutor_delete_tbl_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='student_images/'),
        ),
        migrations.DeleteModel(
            name='StudentImage',
        ),
    ]
