# Generated by Django 5.1.7 on 2025-08-26 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_delete_studentrequest'),
        ('gatepassapp', '0009_tbl_student_image_delete_studentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('category', models.CharField(choices=[('Urgent', 'Urgent'), ('Not Urgent', 'Not Urgent')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('is_leaved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_department')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to='adminapp.tbl_hod')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='gatepassapp.tbl_student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to='adminapp.tbl_tutor')),
            ],
        ),
    ]
