# Generated by Django 5.1.7 on 2025-08-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0010_studentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='forwarded_to_hod',
            field=models.BooleanField(default=False),
        ),
    ]
