# Generated by Django 5.2.6 on 2025-09-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0012_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_student',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
