# Generated by Django 5.2.6 on 2025-09-16 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0013_tbl_student_face_encoding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_student',
            name='face_encoding',
        ),
    ]
