# Generated by Django 5.2.6 on 2025-09-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0015_markattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Not Marked', 'Not Marked')], default='Present', max_length=15),
        ),
    ]
