# Generated by Django 5.2.6 on 2025-09-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0016_alter_markattendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markattendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Not Marked', 'Not Marked')], default='Not Marked', max_length=15),
        ),
    ]
