# Generated by Django 5.2.6 on 2025-09-18 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_tbl_job'),
        ('gatepassapp', '0017_alter_markattendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gatepassapp.tbl_student')),
            ],
        ),
    ]
