# Generated by Django 5.2.6 on 2025-09-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0018_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected by Tutor', 'Rejected by Tutor'), ('Tutor Approved', 'Tutor Approved'), ('Rejected by HOD', 'Rejected by HOD'), ('HOD Approved', 'HOD Approved')], default='Pending', max_length=20),
        ),
    ]
