# Generated by Django 5.2.6 on 2025-09-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0019_studentrequest_qr_code_alter_studentrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentrequest',
            name='is_leaved',
        ),
        migrations.RemoveField(
            model_name='studentrequest',
            name='tutor',
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='forwarded_to_hod',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('HOD Rejected', 'HOD Rejected'), ('HOD Approved', 'HOD Approved')], default='Pending', max_length=20),
        ),
    ]
