# Generated by Django 5.2.6 on 2025-09-30 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_tbl_job'),
        ('gatepassapp', '0020_remove_studentrequest_is_leaved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_requests', to='adminapp.tbl_tutor'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='forwarded_to_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected by Tutor', 'Rejected by Tutor'), ('Tutor Approved', 'Tutor Approved'), ('HOD Rejected', 'HOD Rejected'), ('HOD Approved', 'HOD Approved')], default='Pending', max_length=20),
        ),
    ]
