# Generated by Django 5.2.6 on 2025-09-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepassapp', '0021_studentrequest_tutor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrequest',
            name='is_leaved',
            field=models.BooleanField(default=False),
        ),
    ]
