# Generated by Django 5.2.6 on 2025-11-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatepassapp", "0022_studentrequest_is_leaved"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentrequest",
            name="request_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentrequest",
            name="request_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
