# Generated by Django 5.2.6 on 2025-11-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatepassapp", "0023_studentrequest_request_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Company Reviewed", "Company Reviewed"),
                    ("Company Approved", "Company Approved"),
                    ("Company Rejected", "Company Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
