# Generated by Django 5.2.6 on 2025-11-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatepassapp", "0025_alter_studentrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Rejected by Tutor", "Rejected by Tutor"),
                    ("Tutor Approved", "Tutor Approved"),
                    ("HOD Rejected", "HOD Rejected"),
                    ("HOD Approved", "HOD Approved"),
                    ("Leaved", "Leaved"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
