# Generated by Django 5.2.6 on 2025-11-27 04:35

import django.utils.timezone
import gatepassapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatepassapp", "0026_alter_studentrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(default=gatepassapp.models.get_current_ist_date),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time",
            field=models.TimeField(default=gatepassapp.models.get_current_ist_time),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="applied_at",
            field=models.DateTimeField(
                default=gatepassapp.models.get_current_ist_datetime
            ),
        ),
        migrations.AlterField(
            model_name="markattendance",
            name="date",
            field=models.DateField(default=gatepassapp.models.get_current_ist_date),
        ),
        migrations.AlterField(
            model_name="markattendance",
            name="time",
            field=models.TimeField(default=gatepassapp.models.get_current_ist_time),
        ),
        migrations.AlterField(
            model_name="studentrequest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
