# Generated by Django 5.2.6 on 2025-11-27 10:28

import gatepassapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatepassapp", "0027_alter_attendance_date_alter_attendance_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentrequest",
            name="created_at",
        ),
        migrations.AddField(
            model_name="studentrequest",
            name="ccreated_at",
            field=models.DateTimeField(
                default=gatepassapp.models.get_current_ist_datetime
            ),
        ),
    ]
