# Generated by Django 5.2.6 on 2025-11-27 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gatepassapp", "0028_remove_studentrequest_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentrequest",
            old_name="ccreated_at",
            new_name="created_at",
        ),
    ]
