# Generated by Django 5.2.6 on 2025-12-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gatepassapp", "0029_rename_ccreated_at_studentrequest_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Rejected by Tutor", "Rejected by Tutor"),
                    ("Tutor Approved", "Tutor Approved"),
                    ("HOD Rejected", "HOD Rejected"),
                    ("HOD Approved", "HOD Approved"),
                    ("Leaved", "Leaved"),
                    ("Not Leaved", "Not Leaved"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
