# Generated by Django 5.1.7 on 2025-08-05 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
