# Generated by Django 5.1.7 on 2025-08-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_tbl_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hod_images/')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.tbl_department')),
            ],
        ),
    ]
