# Generated by Django 5.1.7 on 2025-08-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_tbl_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_hod',
            name='roles',
            field=models.CharField(default='hod', max_length=100),
        ),
    ]
