# Generated by Django 5.1.7 on 2025-08-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_tbl_hod_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_hod',
            name='password',
        ),
        migrations.AddField(
            model_name='tbl_hod',
            name='hod_id',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
