# Generated by Django 5.1.7 on 2025-08-20 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_remove_tbl_hod_password_tbl_hod_hod_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('job_type', models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time')], default='full-time', max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('responsibilities', models.TextField(max_length=500)),
                ('qualifications', models.TextField(max_length=500)),
                ('vacancy', models.PositiveIntegerField(default=1)),
                ('passoutyear', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='adminapp.tbl_department')),
            ],
        ),
    ]
