# Generated by Django 5.1.7 on 2025-08-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=255),
        ),
    ]
