# Generated by Django 5.1.7 on 2025-08-20 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_job_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='passoutyear',
        ),
    ]
