# Generated by Django 5.1.7 on 2025-08-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_alter_job_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('langitude', models.FloatField()),
                ('lotitude', models.FloatField()),
            ],
        ),
    ]
