# Generated by Django 5.1.7 on 2025-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_admin',
            name='role',
            field=models.CharField(default='admin', max_length=50),
        ),
    ]
