# Generated by Django 5.1.7 on 2025-08-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_tbl_admin_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_admin',
            old_name='email',
            new_name='admin_email',
        ),
    ]
