# Generated by Django 5.1.7 on 2025-08-23 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_rename_email_tbl_admin_admin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tutor_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tutor_images/')),
                ('roles', models.CharField(default='tutor', max_length=100)),
                ('experience', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_courses', to='adminapp.tbl_course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='adminapp.tbl_department')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hods', to='adminapp.tbl_hod')),
            ],
        ),
    ]
