# Generated by Django 5.1.7 on 2025-08-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_studentrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentRequest',
        ),
    ]
