# Generated by Django 5.1.7 on 2025-08-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_delete_studentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_tutor',
            name='batch',
            field=models.CharField(default='2025-2029', help_text='Format: YYYY-YYYY', max_length=20),
        ),
        migrations.AddField(
            model_name='tbl_tutor',
            name='year',
            field=models.CharField(choices=[('first', 'First Year'), ('second', 'Second Year'), ('third', 'Third Year'), ('fourth', 'Fourth Year')], default='first', max_length=10),
        ),
    ]
