# Generated by Django 5.1.7 on 2025-08-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_tbl_tutor_batch_tbl_tutor_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_tutor',
            name='year',
            field=models.IntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], default=1),
        ),
    ]
