# Generated by Django 5.2.6 on 2025-11-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0022_tbl_job"),
    ]

    operations = [
        migrations.CreateModel(
            name="GateGuard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guard_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="guard_photos/"),
                ),
                ("gate_location", models.CharField(max_length=100)),
            ],
        ),
    ]
