# Generated by Django 5.2.6 on 2025-11-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0023_gateguard"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateguard",
            name="roles",
            field=models.CharField(default="guard", max_length=50),
        ),
    ]
